### ISSUE TITLE
Zattoo Guide Switzerland

### ISSUE THREAD

**Issue by 23matt** [bluezed/FTV-Guide-Repo#1]
Hi there!
Is there a guide for Switzerland with all the Zattoo channels that are available here? I tried the one for Germany but most channels were missing....

Thanks!
Matt

**Comment by bluezed** [comment]
Hi,
sorry, only just saw this...

No, currently there's nothing specifically for Switzerland. However, you can add channels to a custom addons.ini and then create your own guide data via WebGrab+.

Have a look on the forum, there are some threads that explain how to do it in more detail:
http://forums.tvaddons.ag/forums/181-FTV-GUIDE-FOR-KODI

I'm closing this issue as it's not code-related.
