### ISSUE TITLE
Add Seperate Service Addon to reload XMLTV file at Specified time

### ISSUE THREAD

**Issue by bonelifer** [bluezed/FTV-Guide-Repo#3]
It would be nice to have a separate service addon that forces the XMLTV data to be reloaded at a specified time.  Instead of having it reload on first use of the day. I use the XMLTV utility on a separate machine to create the file and scp it to my separate OSMC machines.

**Comment by bluezed** [comment]
There is actually a provision for this built into the original TVGuide but we removed the setting that would activate it as the updating service was causing issues (hangs and crashes) with the guide itself.

If you want to try it out and give feedback we could maybe get it to work in a way that doesn't interfere...
I've added the setting "Update program information on XBMC startup" back in on this branch:
https://github.com/bluezed/FTV-Guide-Repo/tree/experimental/update-service/script.ftvguide

It should trigger an update when Kodi starts. If that works ok we could add some form of time-based solution to this maybe...

Let me know how it goes...

**Comment by bonelifer** [comment]
Works for me. I tried it on my PC running Kodi 16 on Windows 7 and my Raspberry Pi 2 B, running OSMC. Both worked without any weirdness that I could see.

**Comment by bluezed** [comment]
v2.0.20 now has a Background Service setting with interval selection.

Hope it works for you :+1:
