### ISSUE TITLE
Black screen when using Hardware Decoding (Kodi 16)

### ISSUE THREAD

**Issue by bloodhod** [bluezed/FTV-Guide-Repo#6]
When Enabled Hardware decoding on Kodi every other Movies and etc works... But when using Guide and Live TV (PVR Streams) it see Black screen... When Turned to Software decoding and Guide works fine... Can u fix this?

**Comment by bluezed** [comment]
Without more details there's not much I can do as it works fine for me.
Would need your hardware spec, OS, debug log that shows the issue,...
Have you tried switching OSD off in the guide settings?

**Comment by bloodhod** [comment]
Oh Black screen issue now fixed after off OSD. Now it come a new issue

I play the stream and when I press back or stop button it stops the video. But it not get refreshed. See this image... :(
http://i.imgsafe.org/c20aaa2.jpg

If I went page up it get refreshed and again see fine. If I play a video again and stop it then again it see as this image...

**Comment by bluezed** [comment]
Yeah, that's a refresh issue... it's been there pretty much from the beginning. Will need to fix it at some point but not much time atm...

**Comment by bloodhod** [comment]
Mean when u can fix? Is this will take over weeks :( Need this fixed as soon as posible plz?

**Comment by bluezed** [comment]
When I have time for it... most people don't care and it's been like this since the beginning so it's not a priority.
If you need it quicker fix it yourself and do a pull request here. I'll merge it in then.

**Comment by bloodhod** [comment]
Mmmmmm Pull request? Never did that thing before... I will check that....

**Comment by bluezed** [comment]
Guess you'd have to learn to program Python first...

Anyway... don't think I will fix this in the near future as it doesn't bother me enough... :wink:

**Comment by bloodhod** [comment]
Ok... Please fix this... We are a company. But we need to get fixed this... Need to give this to Customers...

As my knowledge it wanna fix on "**onRedrawEPG**"

When going back it runs this
return  # ignore redraw request while redrawing

That's why it not get refreshed... When I remove that it refreshed the Guide. But it shows More layers on program data and get messed... :( Because it redraws the interface with existing current...

Can u check that

**Comment by bluezed** [comment]
Dude, it makes no difference to me if you're a company or whatever. It's your problem that you're using open source software FOR FREE and sell it to your customers.

I'm not getting a penny and I like it that way as I don't have any responsibility and if I don't want to do something I just don't do it. 

If you really need it fixed then hire a programmer and pay for it or fork this project and do your own thing.

I hate people trying to make money from the work others provide for free.

Don't contact me again!
