### ISSUE TITLE
Replace UK Freeview streams with 'Freeview' addons, as opposed to 'FTV' (FilmOn)

### ISSUE THREAD

**Issue by chearmstrong** [bluezed/FTV-Guide-Repo#7]
I seem to be having lots of issues with FilmOn recently, and I've found that they are blocking some addons from using HQ streams - stuff doesn't play in HQ and you need to set the quality to low for it to play.

It would be great if we could use the Freeview addon instead - it has a lot of good (legit) streams from places like BBC iPlayer and TV Player:

https://seo-michael.co.uk/install-freeview-kodi/

Is there any chance of seeing it updated to use this?

**Comment by bluezed** [comment]
I'm not in the UK so cannot use that addon without a VPN.
Is there an actual issue with using that Addon from the guide? 
Have you tried linking your channels in the Guide directly as Favourites in that addon?

The guide isn't actually linked to FlimOn, it's just that we have included the channel links already in the addons.ini. But there's nothing stopping you to create your own ini or link the channels yourself via the Favourites.

Hope that helps.

**Comment by chearmstrong** [comment]
Hi @bluezed - to be honest, I haven't tried linking it to my favourites. I totally forgot I could so that, so apologies. I'll give that a try - I think that will actually be a good solution for me.

Cheers.

**Comment by bluezed** [comment]
Glad to hear that 👍
