### ISSUE TITLE
XMLTV type has no selectable options. 

### ISSUE THREAD

**Issue by remus77** [bluezed/FTV-Guide-Repo#8]
When the script runs it never finds any data and sits "Loading data from external source..." and "Loading of data already in progress..." but never succeeds as there is no configurable XMLTV types in the settings?

**Comment by bluezed** [comment]
Can you provide a full debug log? 

Works fine for me with my own xmltv file...

**Comment by remus77** [comment]
I'm confused. There used to be a number of selectable xmltv types in the settings. UK freeview. Sky. Uk basic etc There are now no xmltv types... Should I be adding one somehow?

**Comment by remus77** [comment]
This is installed from scratch from your own repo on 16.2

**Comment by bluezed** [comment]
Ok, sorry about that... I've not changed anything for quite some time so haven't really been keeping up with things.
Looks like the server the data is pulled from has been switched off or at least the data has been removed by the guy running it. Basically that means you can only use your own Custom Guide data from now on.
To force the setting make sure something like this appears in your settings.xml

```
    <setting id="xmltv.file" value="/home/tv/guide/my_guide.xmltv" />
    <setting id="xmltv.interval" value="2" />
    <setting id="xmltv.refresh" value="false" />
    <setting id="xmltv.type" value="6" />
    <setting id="xmltv.type_select" value="Custom File" />
```

Hope it helps...

**Comment by bluezed** [comment]
Just made an update (v2.0.25a) with a workaround. In case the server is gone you can at least select "Custom File" now.
